---
version: '3.1'

services:
  grafana:
    hostname: grafana
    image: grafana/grafana:latest
    networks:
      - internal
      - external
    expose:
      - 3000
    ports:
      - 3000:3000
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    volumes:
      # - ./grafana/dashboards:/etc/grafana/dashboards:ro
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/provisioning/dashboards/:/var/lib/grafana/dashboards/:ro

  prometheus:
    hostname: prometheus
    image: prom/prometheus:v2.15.2
    networks:
      internal:
    expose:
      - 9090
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/data:/data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--log.level=debug'

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager/config:/prometheus
      - ./alertmanager/data:/data
    command:
      - '--config.file=/prometheus/alertmanager.yml'
      - '--storage.path=/data'
    ports:
      - 9093:9093
    networks:
      - internal
      - external

  netdata:
    image: firehol/netdata:latest
    networks:
      - external
      - internal
    ports:
      - 19998:19999
    volumes:
      - ./netdata.conf:/etc/netdata/netdata.conf

networks:
  external:
  internal:
