---
version: '3.1'
services:
  alerta:
    image: alerta/alerta-web
    volumes:
      - ./alerta/config/alertad.conf:/app/alertad.conf
      - ./alerta/config/alerta.conf:/app/alerta.conf
      - ./alerta/config/config.json:/web/config.json
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - DEBUG=1  # remove this line to turn DEBUG off
      # - BASE_URL=/alerta/api  # NOTE: must end in '/api' then web URL will be '/alerta'
      - AUTH_REQUIRED=True
      - ADMIN_USERS=admin@alerta.io
      - ADMIN_PASSWORD=password
      - ADMIN_KEY=demo-admin-key
      - "COLORS={'severity': {'fatal': '#303030'}, 'text': 'white'}"
      - "SEVERITY={'fatal': 0}"
      - TRACKING_ID=UA-44644195-6
      - PLUGINS=reject,heartbeat,blackout,normalise,enhance
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/alerta
    restart: always
    networks:
      - internal
      - external

  postgres:
    image: postgres:10
    environment:
      - POSTGRES_DB=alerta
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/
    networks:
      - internal
