version: '3'

services:
  grafana:
    build:
      context: grafana
    expose:
      - 3000
    ports:
      - 3000:3000

  timescaledb:
    image: timescale/timescaledb:1.6.0-pg10
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/1-schema.sql
    expose:
      - 5432
    ports:
      - 55435:5432

  #todo add wait-for-it.sh to tsrelay container
  tsrelay:
    image: runejuhl/netdata-tsrelay:latest
    command: 'netdata_tsrelay --dbopts="host=timescaledb port=5432 dbname=metrics user=user1 password=password" -d'

  netdata:
    image: firehol/netdata:latest
    ports:
      - 19999:19999
    volumes:
      - ./netdata.conf:/etc/netdata/netdata.conf
