{
 "title": "Basic metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time),\n  d.metric,\n  d.value::text::float\nFROM\n  netdata,\n  json_each(metrics::json) with ordinality as d(metric,value)\nWHERE\n  d.metric LIKE 'system.cpu.%'\nAND\n  $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time),\n  d.metric,\n  d.value::text::float\nFROM\n  netdata,\n  json_each(metrics::json) with ordinality as d(metric,value)\nWHERE\n  d.metric LIKE 'system.ram.%'\nAND\n  $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time),\n  d.metric,\n  d.value::text::float\nFROM\n  netdata,\n  json_each(metrics::json) with ordinality as d(metric,value)\nWHERE\n  metrics ?| array['system.load.load1']\nAND\n  $__timeFilter(time)\n"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time),\n  d.metric,\n  d.value::text::float\nFROM\n  netdata,\n  json_each(metrics::json) with ordinality as d(metric,value)\nWHERE\n  d.metric LIKE 'disk.%'\nAND\n  $__timeFilter(time)"
    }
   ]
  }
 ]
}